### ISSUE TITLE
Time formatting is only supported for time in seconds

### ISSUE THREAD

**Issue by Niveathika92** [wso2/react-vizgrammar#114]
**Description:**
$subject. The charting library should support the timestamp in milliseconds. A common use case is when siddhi aggregation timestamps in milliseconds

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
0.7.16

**Comment by CharukaK** [comment]
Hi, Time format is supported for the timestamps in milliseconds as shown here in the [sample](https://stackblitz.com/edit/react-vizgrammar-time-bar)

**Comment by CharukaK** [comment]
This works for all the Line, Area and Bar charts

**Comment by Niveathika92** [comment]
It has been documented only under bar charts, https://wso2.github.io/react-vizgrammar/#/bar-charts. Shall we add it to other charts as well?

**Comment by CharukaK** [comment]
It is already documented under Line charts and Area charts as well :)

**Comment by Niveathika92** [comment]
Seems I confused timeStep config with time format. Closing the issue as time format is supported for the millisecond.
