### ISSUE TITLE
[Bar Chart] Y axis labels are cutoff from the edge when they are long enough

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/react-vizgrammar#122]
**Description:**
Y axis labels in the horizontal bar chart are cutoff if they are long enough. Label must have a maximum length to avoid this.

**Affected Product Version:**
SP 4.3-M1

**Steps to reproduce:**
Create a horizontal bar chart with long enough labels to see they are cutoff at the end of the widget boundary

**Comment by suhothayan** [comment]
you can add a length limit so that it will and some ... to the text 
can you try with that ?

**Comment by tharindu-bandara** [comment]
Sure ayya I will
