### ISSUE TITLE
Bar chart width is reducing after each render

### ISSUE THREAD

**Issue by LakshanKarunathilake** [wso2/react-vizgrammar#183]
**Description:**
If the same data provided to a chart and if it has multple state changes related to the other stuff not for the chart, the chart width is getting reduced. after every render. 

**Suggested Labels:**
bug

**Affected Product Version:**
react-vizgrammar : 0.7.33

**Steps to reproduce:**
[https://stackblitz.com/edit/react-vizgrammar-scatterplot?file=index.js](url)

![peek 2019-02-01 10-46](https://user-images.githubusercontent.com/33603053/52104063-b5065700-260e-11e9-9b59-1053e1eea6b8.gif)

**Comment by erangatl** [comment]
Fixed
