### ISSUE TITLE
TimeStamp on ToolTip is not human readable

### ISSUE THREAD

**Issue by LakshanSS** [wso2/react-vizgrammar#199]
**Description:**
Time Stamp in the tooltip is not human readable. It can converted to readable timestamp.

<img width="322" alt="54255160-ee6ea280-457c-11e9-95bd-a1151a419ed3" src="https://user-images.githubusercontent.com/32201965/54413937-86a38d80-471d-11e9-94ee-2b7a6bbe582c.png">

**Affected Product Version:**
0.8.1

**Steps to reproduce:**
[https://stackblitz.com/edit/react-vizgrammar-timestamp-issue?embed=1&file=index.js](https://stackblitz.com/edit/react-vizgrammar-timestamp-issue?embed=1&file=index.js)

**Related Issues:**
[https://github.com/wso2/product-ei/issues/3337](https://github.com/wso2/product-ei/issues/3337)

**Comment by erangatl** [comment]
This can be formatted through
tipTimeFormat - If the x-axis is a time series using this attribute user can format the tick values of the x axis using regex. refer [d3 documentation](https://github.com/d3/d3-time-format/blob/master/README.md#timeFormat) for more info
