### ISSUE TITLE
Implement switching between light and dark themes for samples

### ISSUE THREAD

**Issue by thusithak** [wso2/react-vizgrammar#27]
**Description:**
- Implement a way of switching between material ui light and dark

**Suggested Labels:**
- UX
- Improvement
- Feature

**Suggested Assignees:**
@thusithak @CharukaK

**Comment by CharukaK** [comment]
Currently the switching between dark and light themes is possible for Line, Area, Bar and Pie Charts, themes has to be implemented for table charts, and map charts

**Comment by suhothayan** [comment]
@erangatl can you look into this
