### ISSUE TITLE
Some part of tooltip of point in graphs may not properly display. 

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/react-vizgrammar#46]
**Description:**
some parts of the tooltips are not properly displayed.
![malli3](https://user-images.githubusercontent.com/24618493/33961611-bd2e65d4-e074-11e7-87eb-2d8ca969d07a.png)

**Suggested Labels:**
Type: Bug, Severity : Minor

**Suggested Assignees:**
@CharukaK 

**Affected Product Version:**
productSP: wso2sp-4.0.0-beta3

**Comment by Hafizur046** [comment]
Hey, can anyone help me out? I'm not getting any tooltip what so ever!
![Screenshot_2021-01-12_19-15-29](https://user-images.githubusercontent.com/56998585/104319839-a7042500-550b-11eb-8822-863041e0e2d1.png)
