### ISSUE TITLE
Two types of graphs are displayed. 

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/react-vizgrammar#47]
**Description:**
There are two types of graphs as shown in the image. It is better to have a grid for all graphs. 
![malli4](https://user-images.githubusercontent.com/24618493/33961724-18b4aa44-e075-11e7-8e3e-5a2c6e5df338.png)

**Suggested Labels:**
Type: Bug, Severity: Minor

**Suggested Assignees:**
@CharukaK 

**Affected Product Version:**
productSP: wso2sp-4.0.0-beta3

**OS, DB, other environment details and versions:**
OS: 16.04.1-Ubuntu.
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110

**Comment by CharukaK** [comment]
This issue occurs due to there is one value in the chart's Y-axis when there is more than one value it will show a grid with horizontal lines. Another work around for this issue is defining the yDomain prop in the chart component
