### ISSUE TITLE
For some widgets, text are not visible in light mode

### ISSUE THREAD

**Issue by suganyasuven** [wso2/react-vizgrammar#52]
**Description:**
For some widgets, text are not visible in light mode.
![screenshot from 2017-12-22 11-27-53](https://user-images.githubusercontent.com/30232477/34287200-9bd2682a-e70b-11e7-84f0-296f49f0babe.png)

In this, labels under the chart are not visible.

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-RC2

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Comment by CharukaK** [comment]
Charts in reference are created using the Recharts charting library and therefore not related to this repo.

**Comment by CharukaK** [comment]
created wso2/carbon-dashboards#838

**Comment by lasanthaS** [comment]
Closing this issue as the issue progresses under https://github.com/wso2/carbon-dashboards/issues/838.
